name: SBOM Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  security_repo_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
        with:
          format: cyclonedx-json
          output-file: sbom.cdx.json

      - name: Install grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan for vulnerabilities (table log)
        run: grype sbom:sbom.cdx.json --by-cve --fail-on high -o table

      - name: Scan for vulnerabilities (json report)
        run: grype sbom:sbom.cdx.json --by-cve -o json > grype.json
        if: always()

      - name: Install grant
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grant/main/install.sh | sh -s -- -b /usr/local/bin

      - name: License report
        run: grant list sbom.cdx.json -f=grant.json -v

      - name: Secret scan
        uses: trufflesecurity/trufflehog@0c381f12b3f9a934f33fc61bf003599f5323ff55 # main
        with:
          path: ./
          extra_args: --no-verification --no-update --json

      - name: npm audit
        run: npm audit --audit-level=high

      - name: Upload security reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: security-reports
          path: |
            sbom.cdx.json
            grype.json
            grant.json

